{{- if and .Values.jxRequirements.ingress.domain .Values.jxRequirements.ingress.tls.production }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ .Values.jxRequirements.ingress.tls.email }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsNames:
        - "*.{{ .Values.jxRequirements.ingress.domain }}"
        - "{{ .Values.jxRequirements.ingress.domain }}"
      # ACME DNS-01 provider configurations
      dns01:
{{- if eq .Values.jxRequirements.cluster.provider "gke" }}
        clouddns:
          # The project in which to update the DNS zone
          project: "{{ .Values.jxRequirements.cluster.projectID }}"
          # A secretKeyRef to a google cloud json service account
          serviceAccountSecretRef:
            name: external-dns-gcp-sa
            key: credentials.json
{{- end }}
{{- if eq .Values.jxRequirements.cluster.provider "eks" }}
        route53:
          region: {{ .Values.jxRequirements.cluster.region }}
{{- end }}
{{- end }}
